version: "2.4"

services:  
  ucrustwasm:

    build:
      context: .
      dockerfile: Dockerfile
      
    container_name: yewfaggruppe

    tty: true

    ports:
      - 8080:8080           

    # Mount host directories to container directories
    volumes:
      - './source:/source'
      - '/source/target'

